#version 450

// Vertex inputs.
#define FLINT_VERTEX_INPUT_POSITION			0
#define FLINT_VERTEX_INPUT_NORNAL			1
#define FLINT_VERTEX_INPUT_TANGENT			2
#define FLINT_VERTEX_INPUT_BI_TANGENT		3
#define FLINT_VERTEX_INPUT_COLOR_0			4
#define FLINT_VERTEX_INPUT_COLOR_1			5
#define FLINT_VERTEX_INPUT_COLOR_2			6
#define FLINT_VERTEX_INPUT_COLOR_3			7
#define FLINT_VERTEX_INPUT_COLOR_4			8
#define FLINT_VERTEX_INPUT_COLOR_5			9
#define FLINT_VERTEX_INPUT_COLOR_6			10
#define FLINT_VERTEX_INPUT_COLOR_7			11
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_0  12
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_1  13
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_2  14
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_3  15
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_4  16
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_5  17
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_6  18
#define FLINT_VERTEX_INPUT_TEXTURE_COORD_7  19

// Instance inputs.
#define FLINT_INSTANCE_INPUT_INSTANCE_ID	20
#define FLINT_INSTANCE_INPUT_POSITION 		21
#define FLINT_INSTANCE_INPUT_ROTATION 		22
#define FLINT_INSTANCE_INPUT_SCALE 			23